version: '3'
services:
  musicsync-python:
    container_name: musicsync-python
    build: .
    image: musicsync-python:v1
    restart: always
    volumes:
      - ./src:/usr/src/app
      - music:/usr/src/music
volumes:
  music: {}
